import type { DesktopWfmStatus, LiveTopQuery, LiveTop, RivenAuction, Watch, NewWatch, WatchOutcome, TradeRow, EeLogStatus, NotificationEntry, NotificationPreferences } from './desktop';
import type { UpdateStatus } from './update';
import type { EncryptedBlob } from './encrypted-snapshot';
import type { Inventory, Market, OwnedRecord } from './data';
import type { Catalogs } from '../domain/resolver';
import type { Verdict } from '../domain/advisor';
import type { SessionCandidate, selectSession } from '../domain/trade-session';
import type { BuildPath, BuildPlan, RecipeEntry, SetPart } from '../domain/build-cost';
import type { DucatPlan, ScrapCandidate } from '../domain/ducat-plan';
import type { RelicPlanEntry } from '../domain/relic-planner';
import type { SetReco } from '../domain/set-recos';
import type { AdvisorRequest, HistoryRequest, HistoryAnalysis, SessionRequest, ScoredInventoryFact } from './generated/domain';
export const DESKTOP_CONTEXT = 'tennoworth.desktop';
export interface DesktopServices {
  normalizeInventoryNative(data: Inventory, catalogs: Catalogs, market: Market): Promise<{ owned: Map<string, OwnedRecord>; unresolved: Record<string, number>; flatCount: number }>;
  scoreInventoryNative(owned: Map<string, OwnedRecord>, market: Market, reserveCopies: number, sparesOnly: boolean, availability?: ReadonlyMap<string, number>): Promise<Map<string, ScoredInventoryFact>>;
  evaluateAdvisor(request: AdvisorRequest): Promise<Record<string, Verdict>>;
  evaluateTradeSession(request: Omit<SessionRequest, 'candidates'> & { candidates: SessionCandidate[] }): Promise<ReturnType<typeof selectSession>>;
  evaluateHistory(request: HistoryRequest): Promise<HistoryAnalysis>;
  relicPlan(owned: Map<string, OwnedRecord> | null, market: Market | null, limit?: number): Promise<RelicPlanEntry[]>;
  setRecos(owned: Map<string, OwnedRecord> | null, market: Market | null, limit?: number): Promise<SetReco[]>;
  ducatPlan(owned: Map<string, OwnedRecord> | null, market: Market | null, target: number, keepAbove?: number, availability?: ReadonlyMap<string, number>): Promise<{ candidates: ScrapCandidate[]; plan: DucatPlan }>;
  buildPlan(setSlug: string, setName: string, parts: SetPart[], market: Market | null, owned: Map<string, OwnedRecord> | null, recipes: Record<string, RecipeEntry> | null | undefined): Promise<{ plan: BuildPlan; cheapest: BuildPath | null }>;
  desktopProtectionState(): Promise<import('./protection').ProtectionState>;
  desktopSaveProtectionPlan(plan: import('./protection').ProtectionPlan): Promise<void>;
  updateStatus(): Promise<UpdateStatus>;
  checkUpdate(): Promise<UpdateStatus>;
  installUpdate(): Promise<void>;
  restartApp(): Promise<void>;
  onUpdateAvailable(cb: (s: UpdateStatus) => void): () => void;
  desktopNotifications(): Promise<NotificationEntry[]>;
  desktopWfmStatus(): Promise<DesktopWfmStatus>;
  desktopWfmLogout(): Promise<void>;
  listenForTauriEvent<T>(event: string, cb: (payload: T) => void): () => void;
  desktopAddWatch(watch: NewWatch): Promise<Watch[]>;
  desktopCheckWatchesNow(): Promise<WatchOutcome[]>;
  desktopDeleteWatch(id: number): Promise<Watch[]>;
  desktopListWatches(): Promise<Watch[]>;
  desktopEelogStatus(): Promise<EeLogStatus>;
  desktopListTrades(limit?: number): Promise<TradeRow[]>;
  currentOverlayResult(): Promise<import('./data').RelicOverlayResult | null>;
  desktopNotificationPreferences(): Promise<NotificationPreferences>;
  desktopSaveNotificationPreferences(preferences: NotificationPreferences): Promise<NotificationPreferences>;
  desktopTestNotification(): Promise<string>;
  desktopWfmLogin(email: string, password: string, passphrase: string, platform: string, remember: boolean): Promise<void>;
  desktopWfmUnlock(passphrase: string, remember: boolean): Promise<void>;
  desktopTrySilentUnlock(): Promise<boolean>;
  desktopReadNotifications(id?: number | null): Promise<void>;
  desktopClearNotifications(): Promise<void>;
  desktopLiveTopPrices(queries: LiveTopQuery[]): Promise<LiveTop[]>;
  isDesktopRuntime(): boolean;
  desktopRivenComps(weapon: string): Promise<RivenAuction[]>;
  desktopTradeSessionState(): Promise<import('./data').TradeSessionState>;
  encryptPayload(payload: unknown, passphrase: string): Promise<EncryptedBlob>;
  decryptPayload(blob: EncryptedBlob, passphrase: string): Promise<unknown>;
}
