import { normalizeInventoryNative, scoreInventoryNative } from './inventory-domain';
import { evaluateAdvisor, evaluateTradeSession, evaluateHistory } from './domain-commands';
import { relicPlan, setRecos, ducatPlan, buildPlan } from './planner-domain';
import { desktopAccessStatus, desktopProtectionState, desktopSaveProtectionPlan, currentOverlayResult, desktopNotifications, desktopWfmStatus, desktopWfmLogout, desktopAddWatch, desktopCheckWatchesNow, desktopDeleteWatch, desktopListWatches, desktopEelogStatus, desktopListTrades, desktopNotificationPreferences, desktopSaveNotificationPreferences, desktopTestNotification, desktopWfmLogin, desktopWfmUnlock, desktopTrySilentUnlock, desktopReadNotifications, desktopClearNotifications, desktopLiveTopPrices, desktopRivenComps, desktopTradeSessionState } from './desktop';
import { isDesktopRuntime, desktopOpenExternalUrl } from './runtime';
import { updateDiagnostics, updateStatus, checkUpdate, installUpdate, restartApp, onUpdateAvailable, listenForTauriEvent } from './desktop-update';
import { encryptPayload, decryptPayload } from './encrypted-snapshot';
import type { DesktopServices } from '../contracts/services';
export function createDesktopServices(): DesktopServices { return { desktopAccessStatus, desktopProtectionState, desktopSaveProtectionPlan, normalizeInventoryNative, scoreInventoryNative, evaluateAdvisor, evaluateTradeSession, evaluateHistory, relicPlan, setRecos, ducatPlan, buildPlan, updateDiagnostics, updateStatus, checkUpdate, installUpdate, restartApp, onUpdateAvailable, desktopNotifications, desktopWfmStatus, desktopWfmLogout, listenForTauriEvent, desktopAddWatch, desktopCheckWatchesNow, desktopDeleteWatch, desktopListWatches, desktopEelogStatus, desktopListTrades, currentOverlayResult, desktopNotificationPreferences, desktopSaveNotificationPreferences, desktopTestNotification, desktopWfmLogin, desktopWfmUnlock, desktopTrySilentUnlock, desktopReadNotifications, desktopClearNotifications, desktopLiveTopPrices, isDesktopRuntime, desktopRivenComps, desktopTradeSessionState, encryptPayload, decryptPayload, desktopOpenExternalUrl }; }
